In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### spike_cluster.npy
Cluster for each spike

In [93]:
spk_clusters = np.load('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\ks25\spike_clusters.npy')
df = pd.DataFrame(spk_clusters, columns=['cluster'])
df

cluster
0            198
1            267
2            187
3            183
4             33
...          ...
3340519      307
3340520      198
3340521      145
3340522      170
3340523      307

[3340524 rows x 1 columns]

In [95]:
np.unique(df['cluster'].values).shape

(297,)

In [92]:
np.unique(df['cluster'].values)

array([  0,   1,   2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  14,
        15,  16,  17,  18,  19,  20,  22,  23,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  41,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  89,  91,  92,  93,  94,  95,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 191, 193, 19

In [57]:
np.save('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\ks25\clus_lbl.npy', df['cluster'].values)

#### spike_times.npy
Spikes times for each spike

In [69]:
spk_times = np.load('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\ks25\spike_times.npy')
df = pd.DataFrame(spk_times, columns = ['ts'])
df

ts
0              215
1              221
2              229
3              269
4              272
...            ...
3340519  165975124
3340520  165975128
3340521  165975322
3340522  165975375
3340523  165975382

[3340524 rows x 1 columns]

In [70]:
df['ts'].values

array([      215,       221,       229, ..., 165975322, 165975375,
       165975382], dtype=uint64)

In [59]:
np.save('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\ks25\clus_time.npy', df['ts'].values)

#### cluster_group.tsv
Cluster label (only curated and confirmed!) for each cluster id. If not validated by then there are less clusters than cluster id generated by KS.

In [35]:
clus_group = pd.read_csv('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\AB007_g0_imec0\ks25\cluster_group.tsv', sep='\t')
clus_group

cluster_id group
0            0   mua
1            1   mua
2            2   mua
3            3   mua
4            4   mua
..         ...   ...
88         340  good
89         341  good
90         342  good
91         343  good
92         347  good

[93 rows x 2 columns]

In [36]:
np.unique(clus_group.group, return_counts=True)

(array(['good', 'mua', 'noise'], dtype=object),
 array([67, 17,  9], dtype=int64))

#### cluster_KSlabel.tsv
KS output label for all clusters.

In [37]:
clus_ks = pd.read_csv('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\AB007_g0_imec0\ks25\cluster_KSlabel.tsv', sep='\t')
clus_ks

cluster_id KSLabel
0             0     mua
1             1     mua
2             2     mua
3             3     mua
4             4     mua
..          ...     ...
284         341     mua
285         342     mua
286         343     mua
287         346     mua
288         347     mua

[289 rows x 2 columns]

In [38]:
np.unique(clus_ks.KSLabel, return_counts=True)

(array(['good', 'mua'], dtype=object), array([ 59, 230], dtype=int64))

#### cluster_info.tsv
Info displayed on Phy. Also includes number of spikes and peak channel number for C_waves.

In [29]:
clus_info = pd.read_csv('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\AB007_g0_imec0\ks25\cluster_info.tsv', sep='\t')
clus_info

cluster_id  Amplitude  ContamPct KSLabel         amp  ch  depth  \
0             0     1181.6       77.7     mua   78.235954   0   20.0   
1             1     1334.6        0.0     mua   79.419922   0   20.0   
2             2     1088.7        0.0     mua   81.428429   0   20.0   
3             3      737.8      143.8     mua   58.966412  25  260.0   
4             4      963.8       49.0     mua   73.670265   2   40.0   
..          ...        ...        ...     ...         ...  ..    ...   
292         341      823.4       27.0     mua   67.751808  10  120.0   
293         342      823.4       27.0     mua   67.751808  10  120.0   
294         343      790.9       25.7     mua   65.629524   0   20.0   
295         346     3235.8       27.8     mua  105.748535  69  700.0   
296         347     3235.8       27.8     mua  105.748535  69  700.0   

           fr group  n_spikes  sh  
0    7.031047   mua     38913   0  
1    0.002891   mua        16   0  
2    0.003614   mua        20   0  
3    0.218269   mua      1208   0  
4    4.245044   mua     23494   0  
..        ...   ...       ...  ..  
292  0.258020  good      1428   0  
293  6.273610  good     34721   0  
294  5.423300  good     30015   0  
295  0.063060   NaN       349   0  
296  2.033625  good     11255   0  

[297 rows x 11 columns]

In [33]:
clus_info[clus_info.cluster_id.isin([57])]

cluster_id  Amplitude  ContamPct KSLabel       amp   ch   depth       fr  \
50          57      747.0      134.5     mua  44.55632  147  1480.0  0.10263   

   group  n_spikes  sh  
50   NaN       568   0

In [7]:
clus_info[clus_info['cluster_id']==151]

cluster_id  Amplitude  ContamPct KSLabel         amp   ch   depth  \
140         151     5179.3        8.0    good  123.251617  106  1080.0   

           fr group  n_spikes  sh  
140  0.782552  good      4331   0

There are missing cluster ids, thus the total row number N is lower than max cluster ID number... hence mismatch.
The missing cluster ids are:

In [120]:
missing_cluster_ids = np.asarray([i for i in range(np.max(clus_info.cluster_id)) if i not in np.unique(clus_info.cluster_id)])
missing_cluster_ids

array([  5,  13,  21,  24,  40,  42,  43,  88,  90,  96, 117, 173, 190,
       192, 197, 208, 222, 237, 238, 239, 244, 245, 251, 283, 287, 293,
       294, 296, 303, 309, 310, 312, 313, 314, 315, 316, 319, 321, 322,
       323, 324, 325, 327, 328, 330, 332, 334, 337, 338, 344, 345])

Fill in with missing ids with zeroes... (nan gives weird negative numbers when loading table)

In [131]:
#First set index to cluster_id
clus_info.set_index(keys='cluster_id', drop=False, inplace=True)

In [8]:
#Reindex with missing value
clus_info_all_ids = clus_info.reindex(range(np.max(clus_info.cluster_id)+1), fill_value=0, copy=True)
clus_info_all_ids

cluster_id  Amplitude  ContamPct KSLabel        amp  ch  depth        fr  \
0             0     1181.6       77.7     mua  78.235954   0   20.0  7.031047   
1             1     1334.6        0.0     mua  79.419922   0   20.0  0.002891   
2             2     1088.7        0.0     mua  81.428429   0   20.0  0.003614   
3             3      737.8      143.8     mua  58.966412  25  260.0  0.218269   
4             4      963.8       49.0     mua  73.670265   2   40.0  4.245044   
..          ...        ...        ...     ...        ...  ..    ...       ...   
343           0        0.0        0.0       0   0.000000   0    0.0  0.000000   
344           0        0.0        0.0       0   0.000000   0    0.0  0.000000   
345           0        0.0        0.0       0   0.000000   0    0.0  0.000000   
346           0        0.0        0.0       0   0.000000   0    0.0  0.000000   
347           0        0.0        0.0       0   0.000000   0    0.0  0.000000   

    group  n_spikes  sh  
0     mua     38913   0  
1     mua        16   0  
2     mua        20   0  
3     mua      1208   0  
4     mua     23494   0  
..    ...       ...  ..  
343     0         0   0  
344     0         0   0  
345     0         0   0  
346     0         0   0  
347     0         0   0  

[348 rows x 11 columns]

In [18]:
clus_info_all_ids.group

0      mua
1      mua
2      mua
3      mua
4      mua
      ... 
343      0
344      0
345      0
346      0
347      0
Name: group, Length: 348, dtype: object

In [9]:
clus_info_all_ids[clus_info_all_ids['cluster_id']==151]

cluster_id  Amplitude  ContamPct KSLabel         amp   ch   depth  \
140         151     5179.3        8.0    good  123.251617  106  1080.0   

           fr group  n_spikes  sh  
140  0.782552  good      4331   0

Make clus_table array for C_waves

In [139]:
clus_table = clus_info_all_ids[['n_spikes','ch']]
np.array(clus_table).shape

(348, 2)

In [140]:
np.save('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\ks25\clus_table.npy', np.array(clus_table.values, dtype=np.int32))

In [145]:
clus_tb = np.load('M:\\analysis\Axel_Bisi\mice_data\AB007\Recording\Ephys\AB007_g0\ks25\clus_table.npy')

clus_tb[151]

array([4331,  106])